In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
!pip install numpy


[notice] A new release of pip is available: 24.1.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [4]:
import sys
print(sys.executable)

C:\Users\Student\AppData\Local\Programs\Python\Python312\python.exe


In [5]:
!{sys.executable} -m pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/12.6 MB 9.4 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.6 MB 9.8 MB/s eta 0:00:01
   --------------------- ------------------ 6.8/12.6 MB 11.7 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 11.5 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.6 MB 11.1 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 10.4 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 10.0 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\Student\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [ ]:
# Array Basics

In [7]:
fruits= ['apples', 'banana', 'cherry', 'date'] 

In [8]:
arr_1= np.array(fruits)
print(arr_1)

['apples' 'banana' 'cherry' 'date']


In [9]:
print(arr_1.dtype) # this gives <U6 result. '<' is the byte order or size of the data ! I think. 'U' stands for data type Unicode strings 
#and '6' represnts the number of maximum characters which is banana.

<U6


In [10]:
arr_2 = np.array([[10, 11, 12], [13, 14, 15]])
print(arr_2)


[[10 11 12]
 [13 14 15]]


In [11]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [12]:
arr_3 = np.array([[1, 3, 5], [2, 4, 6]])
print(arr_3)


[[1 3 5]
 [2 4 6]]


In [13]:
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)


[5 4]


In [14]:
arr_5 = np.ones((2, 2, 2))
print(arr_5)


[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
