# Looping Through Arrays


In [3]:
import numpy as np
arrA = np.array([[11, 12, 13] , [14, 15, 16]])
print (arrA)

[[11 12 13]
 [14 15 16]]


In [8]:
for x in arrA:
 print(x * 2)

[22 24 26]
[28 30 32]


In [14]:
for x in arrA:
 for y in x:
     print(y * 2)

22
24
26
28
30
32


The first loop (for x in arrA) multiplies each row as a whole array by 2, displaying each row’s values doubled as arrays. The second loop (for y in x) accesses each individual element within the rows, printing each doubled value on a separate line.

In [16]:
# Loop through the second dimension of arrA, assign each element multiplied by 2 to loop_result, and print it
for x in arrA:
    loop_result= x* 2
    print(loop_result) # This prints each row with all elements multiplied by 2

[22 24 26]
[28 30 32]


### Joining and Stacking Arrays

In [22]:
arrA = np.array([[11, 12, 13] , [14, 15, 16]])
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [23]:
arrA = np.array([[11, 12, 13] , [14, 15, 16]])
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [24]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [26]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [27]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1) 
print(another_2) # I think it does not concatenate b/c it does n't have the same number of raws

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2