In [2]:
import numpy as np

# sample arrays

In [3]:
r_1 = np.random.randint(1, 11, size=(4, 5))


In [4]:
r_2 = np.random.normal(loc=0, scale=1, size=(3, 3))

In [5]:
r_3 = np.random.random(size=(2, 6))

In [6]:
r_4 = np.random.uniform(low=0, high=10, size=(5, 4))

In [7]:
r_5 = np.random.binomial(n=10, p=0.5, size=(3, 2))

In [8]:
print("r_1:", r_1)
print("r_2:", r_2)
print("r_3:", r_3)
print("r_4:", r_4)
print("r_5:", r_5)

r_1: [[3 1 7 8 5]
 [3 1 4 5 8]
 [4 7 3 3 6]
 [6 9 9 2 4]]
r_2: [[-0.29856354  0.71364368  0.79632551]
 [ 1.29325843  0.21666446  0.29393819]
 [ 2.3686884  -1.94519145 -1.01000478]]
r_3: [[0.19784704 0.36738808 0.59294139 0.19956129 0.9982958  0.81478467]
 [0.65829726 0.68672454 0.61768084 0.25050554 0.6028732  0.25563354]]
r_4: [[7.5308088  6.3066419  1.81072429 6.84808317]
 [9.58390184 8.56693221 7.2291879  6.60679256]
 [9.60485045 5.46636315 3.95478178 2.44444655]
 [9.37036336 6.6244036  7.75911677 6.06367921]
 [5.57397154 9.20265102 9.66907787 5.23181693]]
r_5: [[8 5]
 [3 5]
 [5 4]]


# Permutations

In [9]:
r_4 = np.random.uniform(low=0, high=10, size=(5, 4))
print(r_4)

[[0.51991753 3.46485587 6.85757905 8.78770853]
 [5.39255336 2.80320699 0.95980336 0.29006055]
 [3.83968554 2.12457162 1.19496463 3.50100199]
 [4.45884582 5.35034841 5.26741656 1.64445978]
 [4.7977785  3.55191459 2.53562841 6.66217742]]


In [11]:
np.random.shuffle(r_4)
print(r_4)

[[4.45884582 5.35034841 5.26741656 1.64445978]
 [3.83968554 2.12457162 1.19496463 3.50100199]
 [5.39255336 2.80320699 0.95980336 0.29006055]
 [0.51991753 3.46485587 6.85757905 8.78770853]
 [4.7977785  3.55191459 2.53562841 6.66217742]]


In [12]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)

[[3.83968554 2.12457162 1.19496463 3.50100199]
 [4.45884582 5.35034841 5.26741656 1.64445978]
 [4.7977785  3.55191459 2.53562841 6.66217742]
 [5.39255336 2.80320699 0.95980336 0.29006055]
 [0.51991753 3.46485587 6.85757905 8.78770853]]


In [13]:
print(r_4)

[[4.45884582 5.35034841 5.26741656 1.64445978]
 [3.83968554 2.12457162 1.19496463 3.50100199]
 [5.39255336 2.80320699 0.95980336 0.29006055]
 [0.51991753 3.46485587 6.85757905 8.78770853]
 [4.7977785  3.55191459 2.53562841 6.66217742]]


# Mathematical Operations

In [15]:
print(r_1)
print(r_1.shape)

[[3 1 7 8 5]
 [3 1 4 5 8]
 [4 7 3 3 6]
 [6 9 9 2 4]]
(4, 5)


In [16]:
print(r_2)
print(r_2.shape)

[[-0.29856354  0.71364368  0.79632551]
 [ 1.29325843  0.21666446  0.29393819]
 [ 2.3686884  -1.94519145 -1.01000478]]
(3, 3)


In [18]:
result= np.add(r_1, r_2)

print(result)

ValueError: operands could not be broadcast together with shapes (4,5) (3,3) 

In [21]:
shape_result= np.add(r_1.shape, r_2.shape)
print(shape_result)

[7 8]


In [22]:
print(r_1)
print(r_1.shape)

[[3 1 7 8 5]
 [3 1 4 5 8]
 [4 7 3 3 6]
 [6 9 9 2 4]]
(4, 5)


In [23]:
print(r_3)
print(r_3.shape)

[[0.19784704 0.36738808 0.59294139 0.19956129 0.9982958  0.81478467]
 [0.65829726 0.68672454 0.61768084 0.25050554 0.6028732  0.25563354]]
(2, 6)


In [25]:
result13= np.add(r_1, r_3)
print(result13)


ValueError: operands could not be broadcast together with shapes (4,5) (2,6) 

In [28]:
shape_result13= np.add(r_1.shape, r_3.shape)
print(shape_result13)

[ 6 11]


In [29]:
result24= np.add(r_2, r_4)
print(result24)

ValueError: operands could not be broadcast together with shapes (3,3) (5,4) 

In [30]:
shape_result24= np.add(r_2.shape, r_4.shape)
print(shape_result24)

[8 7]


In [31]:
result_r1_r4 = np.add(r_1, r_4)
    print(result_r1_r4)

IndentationError: unexpected indent (3380548334.py, line 2)

In [32]:
result_r3_r4 = np.add(r_3, r_4)
    print(result_r3_r4)

IndentationError: unexpected indent (2049989532.py, line 2)

In [33]:
result_single_element = np.add(r_4, np.array([1]))
print(result_single_element)

[[5.45884582 6.35034841 6.26741656 2.64445978]
 [4.83968554 3.12457162 2.19496463 4.50100199]
 [6.39255336 3.80320699 1.95980336 1.29006055]
 [1.51991753 4.46485587 7.85757905 9.78770853]
 [5.7977785  4.55191459 3.53562841 7.66217742]]


In [34]:
result_single_element_2d = np.add(r_4, np.array([[1]]))
print(result_single_element_2d)

[[5.45884582 6.35034841 6.26741656 2.64445978]
 [4.83968554 3.12457162 2.19496463 4.50100199]
 [6.39255336 3.80320699 1.95980336 1.29006055]
 [1.51991753 4.46485587 7.85757905 9.78770853]
 [5.7977785  4.55191459 3.53562841 7.66217742]]


In [35]:
result_row_array = np.add(r_4, np.array([1, 1, 1, 1, 1]))
    print(result_row_array)

IndentationError: unexpected indent (511305885.py, line 2)

In [36]:
result_column_array = np.add(r_4, np.array([[1], [1]]))
    print(result_column_array)

IndentationError: unexpected indent (2655479930.py, line 2)

# Rounding

In [37]:
r_3 = np.random.random(size=(2, 6)) * 10 
print(r_3)

[[9.37796776 5.5951966  9.93442501 2.21398176 6.13471444 9.13423343]
 [7.80733223 9.52935193 8.63219941 9.46061112 5.48193396 8.52305426]]


In [38]:
trunc_r3 = np.trunc(r_3)
print(trunc_r3)

[[9. 5. 9. 2. 6. 9.]
 [7. 9. 8. 9. 5. 8.]]


In [39]:
fix_r3 = np.fix(r_3)
print(fix_r3)

[[9. 5. 9. 2. 6. 9.]
 [7. 9. 8. 9. 5. 8.]]


In [40]:
floor_r3 = np.floor(r_3)
print(floor_r3)

[[9. 5. 9. 2. 6. 9.]
 [7. 9. 8. 9. 5. 8.]]


In [42]:
ceil_r3 = np.ceil(r_3)
print(ceil_r3)

[[10.  6. 10.  3.  7. 10.]
 [ 8. 10.  9. 10.  6.  9.]]


In [43]:
round_r3 = np.round(r_3, 2)
print(round_r3)

[[9.38 5.6  9.93 2.21 6.13 9.13]
 [7.81 9.53 8.63 9.46 5.48 8.52]]


# Cumulative Operations

In [44]:
r_4 = np.random.uniform(0, 10, size=(5, 4))  
print(r_4)


Original r_4 values:
[[0.05839975 5.76346185 7.6248401  0.19295358]
 [4.28353264 7.9276207  4.49306007 8.02637356]
 [2.74485221 6.49164081 8.83685993 4.17210915]
 [8.36440985 0.77759455 6.15120463 6.45471388]
 [8.58905941 8.56976831 5.98983982 8.14395095]]


In [45]:
total_sum_r4 = np.sum(r_4)
print(total_sum_r4)

113.65624574902024


In [46]:
sum_along_axis_0 = np.sum(r_4, axis=0)
print(sum_along_axis_0)

[24.04025385 29.53008621 33.09580456 26.99010112]


In [47]:
sum_along_axis_1 = np.sum(r_4, axis=1)
print(sum_along_axis_1)

[13.63965527 24.73058697 22.2454621  21.74792291 31.29261849]


In [48]:
cumulative_sum_r4 = np.cumsum(r_4)
print(cumulative_sum_r4)

[5.83997473e-02 5.82186159e+00 1.34467017e+01 1.36396553e+01
 1.79231879e+01 2.58508086e+01 3.03438687e+01 3.83702422e+01
 4.11150945e+01 4.76067353e+01 5.64435952e+01 6.06157043e+01
 6.89801142e+01 6.97577087e+01 7.59089134e+01 8.23636273e+01
 9.09526867e+01 9.95224550e+01 1.05512295e+02 1.13656246e+02]


In [49]:
cumulative_sum_along_axis_0 = np.cumsum(r_4, axis=0)
print(cumulative_sum_along_axis_0)

[[ 0.05839975  5.76346185  7.6248401   0.19295358]
 [ 4.34193239 13.69108254 12.11790017  8.21932714]
 [ 7.0867846  20.18272335 20.95476011 12.39143629]
 [15.45119445 20.9603179  27.10596474 18.84615017]
 [24.04025385 29.53008621 33.09580456 26.99010112]]


# Grocery Problem

In [50]:
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])
print("Contents of bag1:", bag1)
print("Contents of bag2:", bag2)

Contents of bag1: [2 3 4 0]
Contents of bag2: [4 0 1 2]


In [51]:
total_bag1 = np.sum(bag1)
total_bag2 = np.sum(bag2)

In [52]:
print(f"\nThe first bag contains {total_bag1} items, and the second bag contains {total_bag2} items.")


The first bag contains 9 items, and the second bag contains 7 items.


In [53]:
total_items_per_category = bag1 + bag2
total_vegetables, total_fruits, total_snacks, total_beverages = total_items_per_category
print(f"There are {total_vegetables} vegetables, {total_fruits} fruits, {total_snacks} boxes of snacks, and {total_beverages} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


# Teamwork

In [54]:
ali_knocks = np.array([5, 4, 6, 4, 2])
print("Ali's knocks:", ali_knocks)

Ali's knocks: [5 4 6 4 2]


In [55]:
ben_knocks = np.array([0, 5, 5, 3, 4])
print("Ben's knocks:", ben_knocks)

Ben's knocks: [0 5 5 3 4]


In [56]:
carla_knocks = np.array([3, 6, 0, 3, 4])
print("Carla's knocks:", carla_knocks)

Carla's knocks: [3 6 0 3 4]


In [57]:
all_knocks = np.array([ali_knocks, ben_knocks, carla_knocks])
print("\nAll door-knocks for the week:\n", all_knocks)


All door-knocks for the week:
 [[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [58]:
total_knocks_ali = np.sum(ali_knocks)
total_knocks_ben = np.sum(ben_knocks)
total_knocks_carla = np.sum(carla_knocks)

In [59]:
print(f"\nTotal knocks by Ali: {total_knocks_ali}")
print(f"Total knocks by Ben: {total_knocks_ben}")
print(f"Total knocks by Carla: {total_knocks_carla}")


Total knocks by Ali: 21
Total knocks by Ben: 17
Total knocks by Carla: 16


In [60]:
total_knocks_group = np.sum(all_knocks)
print(f"\nTotal knocks by the group: {total_knocks_group}")


Total knocks by the group: 54


In [61]:
daily_knock_totals = np.sum(all_knocks, axis=0)
rolling_total_votes = np.cumsum(daily_knock_totals) * 0.5
print("\nEstimated rolling total of potential voters turned out day by day:\n", rolling_total_votes)


Estimated rolling total of potential voters turned out day by day:
 [ 4.  11.5 17.  22.  27. ]
