In [2]:
import numpy as np

### Generating Random Numbers

In [3]:
r_1 = np.random.randint(1,21, size=2)
print(r_1)

[ 3 20]


In [4]:
r_2 = np.random.randint(1, 21, size=(1,2))
print(r_2)

[[11  4]]


In [6]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.23638988]
 [0.4566023 ]]


In [9]:
r_4 = np.random.randint(20, 100, size=(4,5))
print(r_4)

[[48 21 98 89 50]
 [20 95 63 62 36]
 [69 39 35 53 76]
 [75 78 89 95 72]]


In [11]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.91121505 0.91081853 0.12659748 0.66528387 0.15766733]
 [0.56308011 0.8244212  0.53263694 0.70942001 0.82440461]
 [0.73467118 0.51183844 0.77158328 0.59679553 0.52641012]
 [0.50806038 0.0733324  0.55849668 0.17982227 0.57420231]]


### Generating Random Choices from an Array

In [21]:
students = np.array([ "Fadil Ashiru", "Jacob Ridges","Jennifer Santos", "Jaela J", "Kailyn Mabon", "Martin Reyes", "Mohammad Hadi",
                     "Rodolfo Lopez", "Symone Gant",
                     "Syed Hassan", "Vanessa Guerrero", "Zainab Haseeba"])
print(students)

['Fadil Ashiru' 'Jacob Ridges' 'Jennifer Santos' 'Jaela J' 'Kailyn Mabon'
 'Martin Reyes' 'Mohammad Hadi' 'Rodolfo Lopez' 'Symone Gant'
 'Syed Hassan' 'Vanessa Guerrero' 'Zainab Haseeba']


In [22]:
students_number= len(students)
print(students_number)

12


In [18]:
call_on = np.random.choice(students)
print(call_on)

Martin Reyes


In [32]:
breakout_groups = np.random.choice(students,(3,4), replace=False)
print(breakout_groups)
# This method effectively creates random groups of equal size, which is useful for quick assignments. However,
# it might not always result in balanced groups in terms of skill level.

[['Zainab Haseeba' 'Symone Gant' 'Rodolfo Lopez' 'Jacob Ridges']
 ['Mohammad Hadi' 'Jaela J' 'Jennifer Santos' 'Syed Hassan']
 ['Vanessa Guerrero' 'Fadil Ashiru' 'Kailyn Mabon' 'Martin Reyes']]


In [36]:
probabilities = [0.1, 0.05, 0.1, 0.3, 0.0, 0.05, 0.1, 0.05, 0.1, 0.05, 0.05, 0.05]
print(sum(probabilities))


1.0


In [37]:
call_on_weighted = np.random.choice(students, size=5, p=probabilities, replace=True)
print (call_on_weighted)

['Syed Hassan' 'Symone Gant' 'Fadil Ashiru' 'Vanessa Guerrero'
 'Jennifer Santos']


### Generating a Normal Distribution

In [38]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[14.27583063  6.7653942   9.15192623 15.88575734 17.93492582]
 [19.48857136  6.42094443 13.22893605 -2.39568022  4.00829845]
 [ 6.83076251  5.00582436 13.0060611   5.40778517  8.67709758]
 [ 9.14307954  3.11990311  3.47259072 10.00502096  7.96699083]]
